name = "new-year-music" 
main = "worker.js"
compatibility_date = "2024-01-01"

[assets]
directory = "./"

[[d1_databases]]
binding = "DB"
database_name = "new-year-music"
database_id = "3580cd74-976e-484a-961a-d69e545ffd59"
